apiVersion: v2
name: runpod-kubelet
description: A Helm chart for deploying RunPod Virtual Kubelet
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/kolpakov-p/rnpd
sources:
  - https://github.com/kolpakov-p/rnpd
maintainers:
  - name: kolpakov-p
keywords:
  - runpod
  - virtual-kubelet
  - gpu
  - kubernetes
