apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runpod-kubelet.fullname" . }}
  namespace: {{ .Values.kubelet.namespace }}
  labels:
    {{- include "runpod-kubelet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runpod-kubelet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runpod-kubelet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "runpod-kubelet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--reconcile-interval={{ .Values.kubelet.reconcileInterval }}"
            - "--max-gpu-price={{ .Values.kubelet.maxGpuPrice }}"
            - "--health-server-address={{ .Values.kubelet.healthServerAddress }}"
          ports:
            - name: http
              containerPort: {{ .Values.health.port }}
              protocol: TCP
          {{- if .Values.health.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.health.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.health.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.health.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.runpod.existingSecret | default (include "runpod-kubelet.fullname" .) }}
            - configMapRef:
                name: runpod-kubelet-cluster-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}