{{- if and (not .Values.runpod.existingSecret) .Values.runpod.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runpod-kubelet.fullname" . }}
  namespace: {{ .Values.kubelet.namespace }}
  labels:
    {{- include "runpod-kubelet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.runpod.apiKey }}
  RUNPOD_API_KEY: {{ .Values.runpod.apiKey | quote }}
  {{- end }}
{{- end }}
